version: "3.8"

services:
  write-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123

  read-db:
    image: mongo:latest
    container_name: read-db
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - ./scripts/read-db-init.js:/docker-entrypoint-initdb.d/init.js

  event-store:
    image: mongo:latest
    container_name: event-store
    ports:
      - "27018:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js
